ROOT := ../..
include $(ROOT)/Common.mk

all: r0 r1 r2

r0:
	$(CC) $(CFLAGS) -o r0 r0.c $(LDFLAGS)

r1:
	$(CC) $(CFLAGS) -o r1 r1.c $(LDFLAGS)

r2:
	$(CC) $(CFLAGS) -o r2 r2.c $(LDFLAGS)

include $(ROOT)/Rules.mk
